server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    # true ? ?? ??? ??? ??? ???? ?. ??? ??? ??? ??X ???? ??? ?? ????? false
    register-with-eureka: false
    fetch-registry: false